# Generated by Django 3.1 on 2020-08-21 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='temp_db',
        ),
    ]
